### ISSUE TITLE
SANDBOX Integration. 

### ISSUE THREAD

**Issue by akshaykumar0291** [payu-intrepos/payumoney-new-sample-app#17]
Hi, where should i get the merchant id and key for SANDBOX integration.
I did not find anything on my merchant account.

**Comment by mayur19** [comment]
Please go to integration from navigation bar under dashboard. If you got error then please use credentials give below (Universal credential issued by payumoney itself).

MID : 4934580
Key : rjQUPktU
Salt : e5iIg1jwi8

Below is the test card details for doing a test transaction in the testing mode.

Card No - 5123456789012346
Expiry - 05/2020
CVV - 123
Name - Test

**Comment by akshaykumar0291** [comment]
Thank you for the response.
Could you please tell me for what are parameter i need to generate the hash from server side?

**Comment by mayur19** [comment]
Please refer [this ](https://gist.github.com/mayur19/26417eeba02f5e5ced8138f4d9040d6a)script.

**Comment by akshaykumar0291** [comment]
Thank you, successfully completed.

**Comment by peace-shillong** [comment]
@mayur19 @akshaykumar0291 
Have you kept the default values for surl and furl in the AppEnvironment SANDBOX and PRODUCTION?
Do you have the link to the sample PHP Scripts for succees.php and failure.php, can you kindly share it.

**Comment by mayur19** [comment]
@peace-shillong You can use default values for surl and furl. Basically it is success/failure page which is intended for end user. Best practice is to create our own success/failure page according to theme for great user experience. You need to just show payment successful and payment failed on respective pages.

**Comment by peace-shillong** [comment]
@mayur19 Ok Thank you.
By the way can share the link to the sample success and failure php scripts which i can call from the android app.

**Comment by schezwansoftware** [comment]
> Please go to integration from navigation bar under dashboard. If you got error then please use credentials give below (Universal credential issued by payumoney itself).
> 
> MID : 4934580
> Key : rjQUPktU
> Salt : e5iIg1jwi8
> 
> Below is the test card details for doing a test transaction in the testing mode.
> 
> Card No - 5123456789012346
> Expiry - 05/2020
> CVV - 123
> Name - Test

Thanks Buddy .. These worked for me
