### ISSUE TITLE
Payment Issue

### ISSUE THREAD

**Issue by akshaykumar0291** [payu-intrepos/payumoney-new-sample-app#19]
Hi, when doing the payment after completion of payment i am getting payment failure popup but in my mobile message's inbox and mail, i am getting the success message. 

Also, sometimes its showing application is not responding error while processing payment.
Please help.

**Comment by akshaykumar0291** [comment]
Shall anyone reply for this?

**Comment by Dollymittal21** [comment]
Hi Akshay,

Please drop a mail on techsupport@payumoney.com with the Android SDK version, SURL & FURL, your contact details.

**Comment by smark090** [comment]
hi

**Comment by smark090** [comment]
hello
