### ISSUE TITLE
unable to merge dex

### ISSUE THREAD

**Issue by patelhari** [payu-intrepos/payumoney-new-sample-app#20]
```
1. Error:java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
2. Error:com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
3. Error:com.android.dex.DexException: Multiple dex files define Lcom/android/volley/VolleyError;
```

**Comment by Poras05** [comment]
@Rahul-Hooda i am facing  the same issue with 1.6.0 
but 1.1.0 is fine what is the solution to this.

**Comment by Rahul-Hooda** [comment]
@Poras05 - PnP SDK also uses Volley library internally for network calls. Manifest merger error is caused when your app also uses some version of volley. You can try with below code - 

    implementation ('com.payumoney.sdkui:plug-n-play:1.6.0'){
        exclude group: 'com.android.volley'
    }
