### ISSUE TITLE
Unable to find explicit activity class{com.payumoney.sdkui.ui.activities.PayUmoneyActivity}; have you declared this activity in your AndroidManifest.xml?

### ISSUE THREAD

**Issue by rkandroid** [payu-intrepos/payumoney-new-sample-app#22]
Hello all,
i get this error, and when i add this activity on manifest it's working well so may i know why i need to declare all this activities in manifest ? 

Unable to find explicit activity class {com.rk/com.payumoney.sdkui.ui.activities.PayUmoneyActivity}; have you declared this activity in your AndroidManifest.xml?

Unable to start activity ComponentInfo{com.rk/com.payumoney.core.SdkWebViewActivityNew}: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.rk.cityonline/com.payu.custombrowser.CBActivity}; have you declared this activity in your AndroidManifest.xml?

Unable to find explicit activity class {com.rk/com.payu.custombrowser.CBActivity}; have you declared this activity in your AndroidManifest.xml?

**Comment by Kovartthan** [comment]
How do you solve this issue @rkandroid  ?

**Comment by Mansiwebiots** [comment]
Have you solved this issue @rkandroid ??
