### ISSUE TITLE
 [com.payumoney.sdkui:plug-n-play:1.0.0] AndroidManifest.xml:17:9-36 value=(false).

### ISSUE THREAD

**Issue by rkandroid** [payu-intrepos/payumoney-new-sample-app#23]
May you people pleasae remove **allowBackup=false** attribute from library or make it's value **true** it's clashes with other librarires included in our projects.

Manifest merger failed : Attribute application@allowBackup value=(true) from [ai.devsupport.instamojo:instamojolib:0.1.5] AndroidManifest.xml:12:9-35
is also present at [com.payumoney.sdkui:plug-n-play:1.0.0] AndroidManifest.xml:17:9-36 value=(false).

**Comment by Redman1037** [comment]
You can write `tools:replace="android:allowBackup"`  inside manifest application tag to remove this error.
