### ISSUE TITLE
Please update the sample

### ISSUE THREAD

**Issue by Redman1037** [payu-intrepos/payumoney-new-sample-app#26]
Please update `compileSdkVersion 28` or atleast 27  and your sample is still using 

`'com.payumoney.sdkui:plug-n-play:1.2.0'`   while the latest version according to docs is `'com.payumoney.sdkui:plug-n-play:1.4.1'`  see [ Setting up the PnP SDK](https://developer.payumoney.com/android/)

I tried updating to latest version but `PPConfig` class does not exists in latest version what is the alternative for it

**Comment by deepakbk1** [comment]
same here..

**Comment by DevMobile2** [comment]
I am also getting the same issue.

@Redman1037  did u find any solution.

**Comment by Rahul-Hooda** [comment]
Latest sample app can be accessed from [here](https://github.com/payu-intrepos/payumoney-new-sample-app).
