### ISSUE TITLE
Error converting bytecode to dex:

### ISSUE THREAD

**Issue by Narmadha24** [payu-intrepos/payumoney-new-sample-app#28]
I am getting error like this when I am integrating with my project. I am not using volley but still it displays this error.

Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/android/volley/toolbox/ImageLoader$ImageListener;
Error:com.android.dex.DexException: Multiple dex files define Lcom/android/volley/toolbox/ImageLoader$ImageListener;
Error:	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:661)
Error:	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:616)
Error:	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:598)
Error:	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Error:	at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:61)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:36)
Error:	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
Error:	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
Error:	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
Error:	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
Error:	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error:Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Lcom/android/volley/toolbox/ImageLoader$ImageListener;

**Comment by mayur19** [comment]
First Clean the project and then Make project. Another solution is checkout the libraries which are referring same jar. Look at recently added libraries. 

Have you tried `multiDexEnabled true` in build.gradle ? If not then just add that along with extend your App class with MultiDexApplication.

**Comment by Narmadha24** [comment]
I have done that lot of times. But none works

**Comment by Narmadha24** [comment]
At first I got this error 
Manifest merger failed : Attribute application@allowBackup value=(true) from [ai.devsupport.instamojo:instamojolib:0.1.5] AndroidManifest.xml:12:9-35
is also present at [com.payumoney.sdkui:plug-n-play:1.0.0] AndroidManifest.xml:17:9-36 value=(false).

Then I cleared that error now I am getting this error.

**Comment by mayur19** [comment]
> I have done that lot of times. But none works

Most of the times this issue occurred when two different libraries referring same jar. Check your application.iml file for same jar.

**Comment by Narmadha24** [comment]
Thanks a lot. Now its running. I have lost 2 days for this issue. Thank you so much....

**Comment by mayur19** [comment]
That's great. Please close issue.
