### ISSUE TITLE
Please update sample code to API 28

### ISSUE THREAD

**Issue by tejask4** [payu-intrepos/payumoney-new-sample-app#31]
Hello, I am facing issue when trying to upgrade latest api level 28 from 25. Please provide solution for it,

**Error Log:**
Android resource compilation failed
Output:  ..\payumoney-new-sample-app-master\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1039: error: duplicate value for resource 'attr/layout_anchorGravity' with config ''.
..\payumoney-new-sample-app-master\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1039: error: resource previously defined here.

Command: ..\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\00f07114acd0607d01d550886b39b99f\aapt2-3.2.1-4818971-windows\aapt2.exe compile --legacy \
        -o \
        ..\payumoney-new-sample-app-master\app\build\intermediates\res\merged\debug \
        ..\payumoney-new-sample-app-master\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml
Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #2

Thanks

**Comment by DevMobile2** [comment]
Hi @tejask4 

Iam also facing a similar issue did you find an solution.

**Comment by Rahul-Hooda** [comment]
Please refer to latest sample app from [here](https://github.com/payu-intrepos/payumoney-new-sample-app).
