### ISSUE TITLE
Showing webpage not available after entering card details in latest sdk 1.5.0

### ISSUE THREAD

**Issue by Abdul96881** [payu-intrepos/payumoney-new-sample-app#33]
Showing webpage not available after entering card details in latest sdk 1.5.0

![screenshot_20190208-201954](https://user-images.githubusercontent.com/20418106/52485654-6133d900-2bdf-11e9-8c8a-0e6d6870d2aa.jpg)

**Comment by Abdul96881** [comment]
Kindly check this.

**Comment by malsawmkima** [comment]
the domain should be using HTTPS

if not, try this https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted

**Comment by lonelycowboy** [comment]
the domain should be using HTTPS

if not, try this https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted

**Comment by Abdul96881** [comment]
Thanks now loading fine
