### ISSUE TITLE
Google play store upload time error

### ISSUE THREAD

**Issue by jesikak** [payu-intrepos/payumoney-new-sample-app#36]
implementation 'com.payumoney.sdkui:plug-n-play:1.4.4'
I was used above payumoney sdk.
When i live my app with payUmoney use this two permission **"android.permission.READ_SMS, android.permission.RECEIVE_SMS"** then upload on play store after then give me this below by google play store. 

**Based on our review, we found your app’s expressed user experience did not match your declared core functionality Default SMS handler (and any other core functionality usage while default handler)Default Phone handler (and any other core functionality usage while default handler)Device Automation Please remove these permissions from your app.**

**how to sol this problem.
please reply**

**Comment by Rahul-Hooda** [comment]
Its already resolved in latest release of sdk. Kindly refer it from [here](https://github.com/payu-intrepos/payumoney-new-sample-app). You can also use below gradle to upgrade to latest version -
 implementation 'com.payumoney.sdkui:plug-n-play:1.5.0'
