### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by VivekRai29** [payu-intrepos/payumoney-new-sample-app#39]
Android resource linking failed
C:\Users\quaere 4\.gradle\caches\transforms-2\files-2.1\f547fec302ae04c995f0f9e3e7cb6223\jetified-magicretry-1.0.6\res\layout-v11\magicretry_fragment.xml:121: AAPT: error: resource android:attr/android:progressBarStyleSmall not found.

**Comment by abhinay20392** [comment]
I am also getting same error after I updated Android Studio to version 3.5 and gradle to 3.5.0
Please fix it soon

**Comment by RodoIndia** [comment]
Did you find any solution for it?

**Comment by gaurava-mishra** [comment]
If you are migrated to AndroidX then---
The Temporary Solution is:
1. Create a directory in res folder named "layout-v11"
2. create a file under layout-v11 named "magicretry_fragment.xml"
3. put below code on it.

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:dots="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@android:color/transparent"
    android:clickable="true"
    android:gravity="center"
    android:orientation="vertical">

    <LinearLayout
        android:id="@+id/magic_retry_parent"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginLeft="10dp"
        android:layout_marginRight="10dp"
        android:background="@android:color/white"
        android:gravity="center"
        android:orientation="vertical"
        android:paddingTop="15dp"
        android:paddingBottom="15dp"
        android:visibility="visible">

        <ImageView
            android:id="@+id/retry_btn"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center"
            android:background="@drawable/ripple_drawable"
            android:padding="15dp"
            android:src="@drawable/ic_refresh_black_36dp" />

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="30dp"
            android:gravity="center"
            android:orientation="horizontal">

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="30dp"
                android:layout_marginLeft="5dp"
                android:drawableRight="@drawable/trusticon"
                android:drawablePadding="@dimen/four"
                android:gravity="center_vertical"
                android:textColor="@color/cb_textColor"
                android:textSize="@dimen/twelveScaled"
                android:textStyle="bold" />

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="30dp"
                android:layout_marginLeft="@dimen/four"
                android:drawablePadding="@dimen/four"
                android:gravity="center_vertical"
                android:text="Powered by"
                android:textColor="@color/cb_textColor"
                android:textSize="15sp"
                android:textStyle="normal"

                />

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="20dp"
                android:layout_marginLeft="@dimen/four"
                android:drawableLeft="@drawable/logo_payu"
                android:drawablePadding="@dimen/four"
                android:gravity="center"
                android:textColor="@color/cb_textColor"
                android:textSize="@dimen/twelveScaled"
                android:textStyle="bold" />
        </LinearLayout>

        <TextView
            android:id="@+id/error_title"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center_horizontal"
            android:fontFamily="sans-serif-light"
            android:text="@string/MR_Error_text"
            android:textColor="@android:color/black"
            android:textSize="18sp" />

        <TextView
            android:id="@+id/error_title2"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center_horizontal"
            android:fontFamily="sans-serif-light"
            android:text="@string/MR_Tap_retry_text"
            android:textColor="@android:color/black"
            android:textSize="18sp" />

        


    </LinearLayout>

    <LinearLayout
        android:id="@+id/waiting_dots_parent"
        android:layout_width="100dp"
        android:layout_height="100dp"
        android:background="@android:color/white"
        android:gravity="center"
        android:orientation="vertical"
        android:visibility="gone">


        <ProgressBar
            android:id="@+id/magic_reload_progress"
            style="?android:attr/progressBarStyleSmall"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerInParent="true"
            android:gravity="center"
            android:visibility="gone" />
    </LinearLayout>

</LinearLayout>

**Comment by gaurava-mishra** [comment]
Hey @Team PayU, Since all the development on android start migrating to androidX, you should change your sdk to. Here I am suggesting some changes:

CHANGE:

`<ProgressBar`
            android:gravity="center"
            android:visibility="gone"
            android:id="@+id/magic_reload_progress"
            android:layout_centerInParent="true"
            style="?android:attr/android:progressBarStyleSmall"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content" />`

TO

`<ProgressBar
            android:gravity="center"
            android:visibility="gone"
            android:id="@+id/magic_reload_progress"
            android:layout_centerInParent="true"
            style="?android:attr/progressBarStyleSmall"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content" />`

in file jetified-magicretry-1.0.6/res/layout-v11/magicretry_fragment.xml

**Comment by Rahul-Hooda** [comment]
This issue is fixed in v1.5.0 of PnP. Use below gradle to use it -
implementation 'com.payumoney.sdkui:plug-n-play:1.5.0'
