### ISSUE TITLE
Could not generate hash for "my_merchant_Key"

### ISSUE THREAD

**Issue by amitabha2715** [payu-intrepos/payumoney-new-sample-app#4]
![23146311_1751025894916615_1030655714_n](https://user-images.githubusercontent.com/16895379/32327422-74d94ef4-bffc-11e7-9784-2ba01f06c790.png)

{"status":0,"message":"Could not generate hash for my_merchant_Key, please try with any one payu test credentials {\"LLKwG0\"=>\"qauKbEAJ\", \"gtKFFx\"=>\"eCwWELxi\", \"smsplus\"=>\"admin\", \"0MQaQP\"=>\"13p0PXZk\", \"PqvxqV\"=>\"6SPh4Ulq\", \"obScKz\"=>\"Ml7XBCdR\", \"DXOF8m\"=>\"2Hl5U0En\", \"WhccBa\"=>\"UX5K0KvP\", \"ukgVCk\"=>\"DzSugFtI\", \"ihRGm8\"=>\"2JITyIgq\"}"}

**Comment by shuBomb** [comment]
@amitabha2715  : Did you find any solution?

**Comment by mayur19** [comment]
You must need hash generator script on your server. I hope you are generating hash from server.
In case, if you don't have hash generator script [get it from here](https://gist.github.com/mayur19/26417eeba02f5e5ced8138f4d9040d6a)
Just replace your salt key on that file. Also remove switch case from code you have right now and add following code. Then set merchantHash to mPaymentParams. You can refer the question below for proper request and response handling using volley.

`jsonObject = new JSONObject(response);
merchantHash = jsonObject.getString("result");`

And for reference go through this [stackoverflow answer. ](https://stackoverflow.com/a/47912707/5630823)Please read all comments in answer. You can also refer code from question.
Note: Hash generator algorithm is tested. Send all respective details properly. If possible, do not post any user defined variables.
