### ISSUE TITLE
on click of bank nothing happens

### ISSUE THREAD

**Issue by Narensanju** [payu-intrepos/payumoney-new-sample-app#5]
hi,i have given my merchant key,salt,able to view ui...but no action happens when ank is selected, and given my card details and said paynow, results in payment failure or expired??

**Comment by tarun-wri** [comment]
Same here.. also in add bank account screen nothing happens on click of PAY NOW button. It only validates the Cart No and Expiry field. That's all its doing. Can't add a bank account plus i'm not able to make any payments in Sandbox environment. Getting bank failed to authenticate customer on using any sandbox card details
